# Generated by Django 4.0.5 on 2023-03-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('EventName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=8)),
                ('Name', models.TextField()),
                ('Class', models.CharField(choices=[('9A', ' 9A'), ('9B', ' 9B'), ('10A', ' 10A'), ('10B', ' 10B'), ('11A', ' 11A'), ('11B', ' 11B'), ('11C', ' 11C'), ('12A', ' 12A'), ('12B', ' 12B')], max_length=3)),
                ('Voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('OptionID', models.AutoField(primary_key=True, serialize=False)),
                ('OptionName', models.TextField()),
                ('Votes', models.IntegerField()),
                ('OpitonCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.category')),
                ('OptionEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.event')),
            ],
        ),
    ]
