# Generated by Django 4.0.5 on 2023-03-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='Votes',
            field=models.IntegerField(default=0),
        ),
    ]
