# Generated by Django 4.1.7 on 2023-03-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_alter_option_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="Event",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="vote.event"
            ),
        ),
    ]
