# Generated by Django 4.2.16 on 2025-07-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0004_alter_student_voted"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="OptionImage",
            field=models.ImageField(blank=True, null=True, upload_to="OptionImages"),
        ),
        migrations.AlterField(
            model_name="student",
            name="Class",
            field=models.CharField(
                choices=[
                    ("AA", " Aa"),
                    ("BB", " Bb"),
                    ("6A", " 6A"),
                    ("6B", " 6B"),
                    ("7A", " 7A"),
                    ("7B", " 7B"),
                    ("8A", " 8A"),
                    ("8B", " 8B"),
                    ("9A", " 9A"),
                    ("9B", " 9B"),
                    ("10A", " 10A"),
                    ("10B", " 10B"),
                    ("11A", " 11A"),
                    ("11B", " 11B"),
                    ("12A", " 12A"),
                    ("12B", " 12B"),
                    ("12C", " 12C"),
                ],
                max_length=3,
            ),
        ),
    ]
